version: '3.0'
services:
  thunderbird-dev:
    image: pcic/thunderbird:latest
    container_name: thunderbird-dev
    environment:
      - PYWPS_CFG=/wps.cfg
    ports:
      - "30099:5000"
    volumes:
      - ./dev-component/wps.cfg:/wps.cfg
    restart: always

networks:
  default:
    external:
      name: pcicbr0


# docker-compose build
# docker-compose up
# docker-compose down
# docker-compose rm
