name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install cdo
        python -m pip install --upgrade pip
        pip install -i https://pypi.pacificclimate.org/simple/ -r requirements_dev.txt
    - name: Code Quality
      run: black . --check
    - name: Run Tests with pytest
      run: pytest -m "not online" tests/ -v
